name: mathopt
channels:
  - defaults
dependencies:
  - cvxopt=1.2.0
  - networkx=2.6
  - scipy=1.6
  - pandas=1.4.3
  - seaborn=0.11.2
  - joblib=1.1.0
  - flask=2.0
  - pip
  - pip:
    - matplotlib
    - pulp
    - pycddlib
    - vpython
    - picos